# Generated by Django 3.1.7 on 2021-06-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user', models.CharField(max_length=100)),
                ('cctv_name', models.CharField(max_length=100)),
                ('server_url', models.CharField(max_length=200)),
                ('mask_detection', models.BooleanField()),
                ('social_distance', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Telegram_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
    ]
